version: '3.7'

services:
  pocket:
    container_name: pocket
    cap_add:
    - ALL
    build: ./pocket/
    ports:
    - "8081:8081"
    - "26656:26656"
    - "26657:26657"
    volumes:
    - "./data/.pocket/:/root/.pocket/"
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  indexer:
    container_name: indexer
    build: ./backend
    env_file:
      - .env
    depends_on:
      - pocket
      - db
  postgres:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  static:


