version: '3.7'

services:
  pocket:
    container_name: pocket
    cap_add:
    - ALL
    build: ./pocket/
    ports:
    - "26657:26657"
    - "8081:8081"
    - "26656:26656"
    volumes:
    - "./data/.pocket/:/root/.pocket/"
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - .env
    depends_on:
      - pocket
      - postgres
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  static:


