"""
Django settings for poktwatch project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'si+pj1e*xir)-p1v0_##^w6)n$p)sc(0v9dvl6-(ts&0w&qsaa'
#SECRET_KEY = os.getenv('SECRET_KEY')
#DEBUG = os.getenv('DEBUG')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#SECURE_SSL_REDIRECT = False
ALLOWED_HOSTS = ["*"]
#ALLOWED_HOSTS = ["poktwatch.io",  "http://www.poktwatch.io/", "https://www.poktwatch.io/", "www.poktwatch.io"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathfilters',
    'explorer',
    'analytics'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'poktwatch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'poktwatch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'dbjcte3ojl6ska',
#         'USER': 'ibclhcjiwsbxnn',
#         'PASSWORD': 'be5454e4edab439fdc807a97252fffea1fe3917a76aabfbccd823b6239c6295f',
#         'HOST': 'ec2-3-221-100-217.compute-1.amazonaws.com',
#         'PORT':  5432,
#     }
# }

# #standard-0
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'poktwatch',
#        'USER': 'postgres',
#	'PASSWORD':'ok',        
#        'HOST': 'localhost',
#        'PORT':  5432,
#    },
#    'thunderhead': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'd2lmlbrc00agoq',
#        'USER': 'jdddvjrpsrdwhx',
#        'PASSWORD': 'a5fa1a86c1b64b2cb27eae3d5d812dada351f95d19aee1ba7fb0e5a3015d4763',
#        'HOST': 'ec2-52-3-130-181.compute-1.amazonaws.com',
#        'PORT':  5432,
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT': 5432,
    }
}

# standard-2
# DATABASES = {
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     #     'NAME': 'dfj22uqqfkqbam',
#     #     'USER': 'u8ubp48c0q5bhm',
#     #     'PASSWORD': 'pdfa73ca4ff5e08f37c37d656332e303aa4e5f150734fb8b2c0b3fa344590f4e8',
#     #     'HOST': 'ec2-35-170-124-67.compute-1.amazonaws.com',
#     #     'PORT':  5432,
#     # },
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     #     'NAME': 'poktwatch',
#     #     'USER': 'postgres',
#     #     'PASSWORD': 'ok',
#     #     'HOST': 'localhost',
#     #     'PORT':  5432,
#     # },
#     'thunderhead': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd2lmlbrc00agoq',
#         'USER': 'jdddvjrpsrdwhx',
#         'PASSWORD': 'a5fa1a86c1b64b2cb27eae3d5d812dada351f95d19aee1ba7fb0e5a3015d4763',
#         'HOST': 'ec2-52-3-130-181.compute-1.amazonaws.com',
#         'PORT':  5432,
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = '/static'
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join((BASE_DIR), 'explorer/static'),
)

# django_heroku.settings(locals())
